server:
  port: 0 # random port

spring:
  application:
    name: account-service

  jpa:
    show-sql: true

  datasource:
    url: jdbc:postgresql://localhost:5432/imagespace_account_db #postgres
    username: root
    password: root

  kafka:
    consumer:
      group-id: account-service
      auto-offset-reset: latest
    # change this property if you are using your own
    # Kafka cluster or your Docker IP is different
    bootstrap-servers: 127.0.0.1:9092

kafka-properties:
  topics:
    post: post-topic
    source: source-topic
    subscription: subscription-topic
  events:
    create-post: create-post-event
    create-source: create-source-event
    delete-source: delete-source-event
    update-subscription-priority: update-subscription-priority
  msg-per-request: 1

cache:
  duration: 1 # minutes

logging:
  level:
    org.springframework.web.reactive.function.server.RouterFunctions: DEBUG
