server:
  port: 0 # random port

spring:
  application:
    name: account-service

  jpa:
    show-sql: true

  datasource:
    url: jdbc:postgresql://localhost:5432/imagespace_account_db #postgres
    username: root
    password: root

cache:
  duration: 1 # minutes

logging:
  level:
    org.springframework.web.reactive.function.server.RouterFunctions: DEBUG
