server:
  port: 8081

spring:
  application:
    name: post-service

  jpa:
    show-sql: true

  datasource:
    url: jdbc:postgresql://localhost:5432/imagespace_post_db #postgres
    username: root
    password: root

  kafka:
    consumer:
      group-id: post-service
      auto-offset-reset: earliest
    # change this property if you are using your own
    # Kafka cluster or your Docker IP is different
    bootstrap-servers: localhost:9092

kafka-properties:
  post-topic-name: post-topic
  like-topic-name: like-topic
  create-post-event-name: create-post-event
  delete-post-event-name: delete-post-event
  msg-per-request: 1

cache:
  duration: 1 # minutes

logging:
  level:
    org.springframework.web.reactive.function.server.RouterFunctions: DEBUG
