server:
  port: 0 # random port

spring:
  application:
    name: source-service

  data:
    mongodb:
      database: image-space-source-storage
      host: localhost
      port: 27017

  kafka:
    consumer:
      group-id: source-service
      auto-offset-reset: latest
#      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
#      properties:
#        spring:
#          json:
#            trusted:
#              packages: '*'
    # change this property if you are using your own
    # Kafka cluster or your Docker IP is different
    bootstrap-servers: 127.0.0.1:9092

kafka-properties:
  source-topic-name: source-topic
  create-source-event-name: create-source-event
  delete-source-event-name: delete-source-event
  msg-per-request: 1

feign:
  hystrix:
    enabled: true
  client:
    config:
      feignName:
        connectTimeout: 90000
        readTimeout: 90000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

ribbon:
  eager-load:
    enabled: true
    clients: post-service

logging:
  level:
    org.springframework.web.reactive.function.server.RouterFunctions: DEBUG

source:
  properties:
    source-high: 720
    source-width: 540
    source-preview-high: 320
    source-preview-width: 320
    source-small-high: 120
    source-small-width: 120