server:
  port: 8080

logging:
  level:
    org.springframework.web.reactive.function.server.RouterFunctions: DEBUG

security:
  properties:
    client-id: image-space-client
    # image-space-secret
    client-secret: $2a$04$i0gM/CmwfDpItrdD82Sa2eJTAOGj33xILUlznfmuUJ64MW46Mb6qm
    grant-type-password: password
    authorization-code: authorization_code
    refresh-token: refresh_token
    implicit: implicit
    scope-read: read
    scope-write: write
    trust: trust
    access-token-validity-seconds: 3600
    refresh-token-validity-seconds: 21600
