server:
  port: 8080

spring:
  application:
    name: api-server

  kafka:
    # change this property if you are using your own
    # Kafka cluster or your Docker IP is different
    bootstrap-servers: localhost:9092

kafka-properties:
  img-topic-name: img-event-topic
  msg-per-request: 1

feign:
  hystrix:
    enabled: true
  client:
    config:
      feignName:
        connectTimeout: 90000
        readTimeout: 90000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

ribbon:
  eager-load:
    enabled: true
    clients: core-service

logging:
  level:
    org.springframework.web.reactive.function.server.RouterFunctions: DEBUG

security:
  properties:
    client-id: image-space-client
    # image-space-secret
    client-secret: $2a$04$i0gM/CmwfDpItrdD82Sa2eJTAOGj33xILUlznfmuUJ64MW46Mb6qm
    grant-type-password: password
    authorization-code: authorization_code
    refresh-token: refresh_token
    implicit: implicit
    scope-read: read
    scope-write: write
    trust: trust
    access-token-validity-seconds: 3600
    refresh-token-validity-seconds: 21600
