server:
  port: 8080

spring:
  jpa:
    show-sql: true

  datasource:
    url: jdbc:mysql://localhost:3306/imagespacedb
    username: root
    password: root

logging:
  level:
    org.springframework.web.reactive.function.server.RouterFunctions: DEBUG