server:
  port: 8080

spring:
  jpa:
    show-sql: true

  datasource:
    url: jdbc:mysql://localhost:3306/imagespacedb
    username: root
    password: root

logging:
  level:
    org.springframework.web.reactive.function.server.RouterFunctions: DEBUG

security:
  properties:
    client-id: image-space-client
    client-secret: $2a$04$e/c1/RfsWuThaWFCrcCuJeoyvwCV0URN/6Pn9ZFlrtIWaU/vj/BfG
    grant-type-password: password
    authorization-code: authorization_code
    refresh-token: refresh_token
    implicit: implicit
    scope-read: read
    scope-write: write
    trust: trust
    access-token-validity-seconds:
    refresh-token-validity-seconds:
