server:
  port: 8000

spring:
  application:
    name: core-server

  jpa:
    show-sql: true

  datasource:
    url: jdbc:postgresql://localhost:5432/imagespacedb #postgres
    username: root
    password: root

logging:
  level:
    org.springframework.web.reactive.function.server.RouterFunctions: DEBUG
