server:
  port: 8081

spring:
  application:
    name: post-server

  jpa:
    show-sql: true

  datasource:
    url: jdbc:postgresql://localhost:5432/imagespace_post_db #postgres
    username: root
    password: root

cache:
  duration: 10 # minutes

logging:
  level:
    org.springframework.web.reactive.function.server.RouterFunctions: DEBUG
