server:
  port: 8040

spring:
  application:
    name: source-server

  data:
    mongodb:
      database: image-space-source-storage
      host: localhost
      port: 27017
      username: mongodb

  kafka:
    consumer:
      group-id: img-events
      auto-offset-reset: none
    # change this property if you are using your own
    # Kafka cluster or your Docker IP is different
    bootstrap-servers: localhost:9092

kafka-properties:
  img-topic-name: img-event-topic
  msg-per-request: 1

feign:
  hystrix:
    enabled: true
  client:
    config:
      feignName:
        connectTimeout: 90000
        readTimeout: 90000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

ribbon:
  eager-load:
    enabled: true
    clients: core-service

logging:
  level:
    org.springframework.web.reactive.function.server.RouterFunctions: DEBUG